---

- name: Remove ECDSA host key
  file:
    path: {{item}}
    state: absent
  with_items:
    - /etc/ssh/ssh_host_ecdsa_key
    - /etc/ssh/ssh_host_ecdsa_key.pub
  notify: restart sshd

- name: Re-config sshd
  copy:
    dest: /etc/ssh/{{item}}
    src: sshd/{{item}}
  with_items:
    - ssh_config
    - sshd_config
    - moduli
    - sshd_config.d/ca.conf
    - sshd_config.d/trustedCAs.pub
  notify: restart sshd

- name: Change default port for sshd
  template:
    dest: /etc/ssh/sshd_config.d/move_port.conf
    src: ssh_port_setting.j2
    owner: root
    group: wheel
    mode: '0440'
  notify: restart sshd

- name: Re-generate host keys
  shell: ssh-keygen -q -N '' -C '' -b 4096 -t {{item}} -f /etc/ssh/ssh_host_{{item}}_key
  with_items:
    - ed25519
    - rsa
  notify: restart sshd

- name: Get certification access parameters

- name: Certify ssh host keys
  uri:
    method: POST
    url: "{{ certify_url }}"
    body_format: form-multipart
    return_content: true
    status_code: [ 200 ]
    headers:
      {{ certification_token_name }}: "{{ certification_token }}"
    body:
      "ssh_host_{{item}}_key.pub":
        filename: /etc/ssh/ssh_host_{{item}}_key.pub
        mime_type: application/octet-stream
  with_items:
    - ed25519
    - rsa
  when: certify_url is defined and certify_url != ""
  notify: restart sshd
  register: cert_pubs
